version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/data/rabbitmq
    networks:
      - my-network

  mongodb:
    image: mongo:6.0 
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

  access-control:
    image: vu0203/node-microservice-user
    ports:
      - "6001:6001"
    restart: unless-stopped
    environment:
      - PORT=6001
      - URL_MONGO=mongodb://mongodb:27017/user-service
      - URL_RABBITMQ=amqp://rabbitmq:5672
    networks:
      - my-network

  audit-log:
    image: vu0203/node-microservice-chat
    ports:
      - "6002:6002"
    restart: unless-stopped
    environment:
      - PORT=6002
      - URL_MONGO=mongodb://mongodb:27017/user-service
      - URL_RABBITMQ=amqp://rabbitmq:5672
    networks:
      - my-network

  data-share:
    image: vu0203/node-microservice-notification
    ports:
      - "6003:6003"
    restart: unless-stopped
    environment:
      - PORT=6003
      - URL_MONGO=mongodb://mongodb:27017/user-service
      - URL_RABBITMQ=amqp://rabbitmq:5672
    networks:
      - my-network
  
  hospital:
    image: vu0203/node-microservice-notification
    ports:
      - "6004:6004"
    restart: unless-stopped
    environment:
      - PORT=6004
      - URL_MONGO=mongodb://mongodb:27017/user-service
      - URL_RABBITMQ=amqp://rabbitmq:5672
    networks:
      - my-network
  
  patients-management:
    image: vu0203/node-microservice-notification
    ports:
      - "6005:6005"
    restart: unless-stopped
    environment:
      - PORT=6005
      - URL_MONGO=mongodb://mongodb:27017/user-service
      - URL_RABBITMQ=amqp://rabbitmq:5672
    networks:
      - my-network
      
volumes:
  mongo-data:
  rabbitmq-data:

networks:
  my-network:
     driver: overlay
