version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/data/rabbitmq
    networks:
      - my-network

  mongodb:
    image: mongo:6.0 
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

  user:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - PORT=3000
      - URL_MONGO=mongodb://mongodb:27017/user-service
      - URL_RABBITMQ=amqp://rabbitmq:5672
    networks:
      - my-network

  chat:
    build: 
      context: ./chat-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - PORT=3001
      - URL_MONGO=mongodb://mongodb:27017/user-service
      - URL_RABBITMQ=amqp://rabbitmq:5672
    networks:
      - my-network

  notification:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - PORT=3002
      - URL_MONGO=mongodb://mongodb:27017/user-service
      - URL_RABBITMQ=amqp://rabbitmq:5672
    networks:
      - my-network

  kong-database:
    image: postgres:13
    restart: unless-stopped
    networks:
      - kong-net
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    ports:
      - "5432:5432"

  kong-gateway:
    image: kong/kong-gateway:3.8.0.0
    restart: unless-stopped
    depends_on:
      - kong-database
    networks:
      - kong-net
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_LICENSE_DATA
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
      
volumes:
  mongo-data:
  rabbitmq-data:

networks:
  my-network:
    driver: bridge
  kong-net:
    driver: bridge
